baseURL = "https://www.frankliu.org/easyhugo/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "ananke"
# canonifyURLs = true
ignoreFiles = [ "^\\.#", "^#" ]
[params]
	custom_css = ["css/custom.css"]

[markup]
	[markup.goldmark]
		[markup.goldmark.renderer]
			unsafe = true
